### ISSUE TITLE
Fragment 缺少空构造异常

### ISSUE THREAD

**Issue by dodocat** [mingcheng/Tracker#10]
``` bash
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.gracecode.tracker/com.gracecode.tracker.ui.activity.Detail}: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment com.gracecode.tracker.ui.fragment.ArchiveMetaTimeFragment: make sure class name exists, is public, and has an empty constructor that is public
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2339)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2389)
            at android.app.ActivityThread.access$600(ActivityThread.java:153)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1269)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5289)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment com.gracecode.tracker.ui.fragment.ArchiveMetaTimeFragment: make sure class name exists, is public, and has an empty constructor that is public
            at android.support.v4.app.Fragment.instantiate(Fragment.java:413)
            at android.support.v4.app.FragmentState.instantiate(Fragment.java:97)
            at android.support.v4.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:1783)
            at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:213)
            at com.gracecode.tracker.ui.activity.base.Activity.onCreate(Activity.java:38)
            at com.gracecode.tracker.ui.activity.Detail.onCreate(Detail.java:42)
            at android.app.Activity.performCreate(Activity.java:5133)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2293)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2389)
            at android.app.ActivityThread.access$600(ActivityThread.java:153)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1269)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5289)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.InstantiationException: can't instantiate class com.gracecode.tracker.ui.fragment.ArchiveMetaTimeFragment; no empty constructor
            at java.lang.Class.newInstanceImpl(Native Method)
            at java.lang.Class.newInstance(Class.java:1130)
            at android.support.v4.app.Fragment.instantiate(Fragment.java:402)
            at android.support.v4.app.FragmentState.instantiate(Fragment.java:97)
            at android.support.v4.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:1783)
            at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:213)
            at com.gracecode.tracker.ui.activity.base.Activity.onCreate(Activity.java:38)
            at com.gracecode.tracker.ui.activity.Detail.onCreate(Detail.java:42)
            at android.app.Activity.performCreate(Activity.java:5133)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2293)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2389)
            at android.app.ActivityThread.access$600(ActivityThread.java:153)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1269)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5289)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
            at dalvik.system.NativeStart.main(Native Method)
11-26 22:25:49.032    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:25:49.227    9420-9420/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:25:49.250    9420-9420/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:25:54.039    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:25:59.024    8574-9294/com.google.android.apps.plus E/EsSyncAdapterService﹕ [bux] failed due to exception: java.net.UnknownHostException: Unable to resolve host "www.googleapis.com": No address associated with hostname
11-26 22:25:59.024    8574-9294/com.google.android.apps.plus E/EsSyncAdapterService﹕ Cannot get account status
11-26 22:25:59.039    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:26:04.039    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:26:06.289    6760-9362/com.taobao.taobao:PushService_v1 E/SyncHttp.client﹕ request url error:[http://apoll.m.taobao.com/activeip/]
11-26 22:26:06.289    6760-9362/com.taobao.taobao:PushService_v1 E/HostClient﹕ host exception
11-26 22:26:09.039    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:26:11.149    9420-9420/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:26:12.117    6760-6994/com.taobao.taobao:PushService_v1 E/SyncHttp.client﹕ request url error:[http://apoll.m.taobao.com/activeip/]
11-26 22:26:12.117    6760-6994/com.taobao.taobao:PushService_v1 E/HostClient﹕ host exception
11-26 22:26:14.039    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:26:19.039    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:26:20.828    4078-9401/com.codoon.gps:pushservice_v1 E/PushConnection﹕ Create socket err, errno:0
11-26 22:26:24.024  17930-25134/com.zhihu.daily.android E/AVOS_PUSH﹕ Unable to resolve host "router.push.avoscloud.com": No address associated with hostname
11-26 22:26:24.039    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:26:29.039    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:26:34.032    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:26:39.039    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:26:44.039    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:26:49.039    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:26:52.133    6760-9362/com.taobao.taobao:PushService_v1 E/SyncHttp.client﹕ request url error:[http://apoll.m.taobao.com/activeip/]
11-26 22:26:52.133    6760-9362/com.taobao.taobao:PushService_v1 E/HostClient﹕ host exception
11-26 22:26:54.039    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:26:57.985    6760-6994/com.taobao.taobao:PushService_v1 E/SyncHttp.client﹕ request url error:[http://apoll.m.taobao.com/activeip/]
11-26 22:26:57.985    6760-6994/com.taobao.taobao:PushService_v1 E/HostClient﹕ host exception
11-26 22:26:59.039    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:27:04.039    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:27:04.071  17930-25134/com.zhihu.daily.android E/com.avos.avospush.push.AVPushConnectionManager﹕ Failed to connect to push server
11-26 22:27:09.039    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:27:14.039    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:27:19.039    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:27:24.039    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:27:29.039    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:27:34.047    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:27:37.992    6760-9362/com.taobao.taobao:PushService_v1 E/SyncHttp.client﹕ request url error:[http://apoll.m.taobao.com/activeip/]
11-26 22:27:37.992    6760-9362/com.taobao.taobao:PushService_v1 E/HostClient﹕ host exception
11-26 22:27:39.047    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:27:43.860    6760-6994/com.taobao.taobao:PushService_v1 E/SyncHttp.client﹕ request url error:[http://apoll.m.taobao.com/activeip/]
11-26 22:27:43.860    6760-6994/com.taobao.taobao:PushService_v1 E/HostClient﹕ host exception
11-26 22:27:44.047    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:27:44.125  17930-17958/com.zhihu.daily.android E/AVOS_PUSH﹕ Unable to resolve host "router.push.avoscloud.com": No address associated with hostname
11-26 22:27:49.047    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:27:54.039    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:27:59.047    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:28:04.047    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:28:09.047    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:28:14.047    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:28:19.047    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:28:23.860    6760-9362/com.taobao.taobao:PushService_v1 E/SyncHttp.client﹕ request url error:[http://apoll.m.taobao.com/activeip/]
11-26 22:28:23.860    6760-9362/com.taobao.taobao:PushService_v1 E/HostClient﹕ host exception
11-26 22:28:24.047    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:28:24.180  17930-17958/com.zhihu.daily.android E/com.avos.avospush.push.AVPushConnectionManager﹕ Failed to connect to push server
11-26 22:28:29.047    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:28:29.711    6760-6994/com.taobao.taobao:PushService_v1 E/SyncHttp.client﹕ request url error:[http://apoll.m.taobao.com/activeip/]
11-26 22:28:29.711    6760-6994/com.taobao.taobao:PushService_v1 E/HostClient﹕ host exception
11-26 22:28:34.047    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:28:39.047    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:28:42.102    4078-9554/com.codoon.gps:pushservice_v1 E/PushConnection﹕ Create socket err, errno:0
11-26 22:28:44.047    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:28:49.047    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:28:54.047    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:28:59.047    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:29:04.047    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:29:04.110    9588-9588/com.tencent.mobileqq:qzone E/dalvikvm﹕ Could not find class 'com.tencent.msf.service.protocol.security.AppidList', referenced from method mqq.app.BuiltInServlet.service
11-26 22:29:09.047    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:29:09.727    6760-9362/com.taobao.taobao:PushService_v1 E/SyncHttp.client﹕ request url error:[http://apoll.m.taobao.com/activeip/]
11-26 22:29:09.727    6760-9362/com.taobao.taobao:PushService_v1 E/HostClient﹕ host exception
11-26 22:29:14.047    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:29:15.578    6760-6994/com.taobao.taobao:PushService_v1 E/SyncHttp.client﹕ request url error:[http://apoll.m.taobao.com/activeip/]
11-26 22:29:15.578    6760-6994/com.taobao.taobao:PushService_v1 E/HostClient﹕ host exception
11-26 22:29:19.055    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:29:22.149    4078-9578/com.codoon.gps:pushservice_v1 E/PushConnection﹕ Create socket err, errno:0
11-26 22:29:24.047    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:29:29.047    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:29:34.047    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:29:34.735    9588-9603/com.tencent.mobileqq:qzone E/QZLog﹕ [E]getconfig[76951] return 1002 timestamp[app2msf:1385476144632,msf2net:-1385476144632,net2msf:30103,msf2app:30103] errMsg:wait serverResp timeout
11-26 22:29:37.860    9640-9651/? E/SQLiteLog﹕ (1) no such table: Account
11-26 22:29:39.047    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:29:40.969    9420-9420/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:29:42.602    9588-9603/? E/QZLog﹕ [E]getUserLogoTimestamp[76954] return 1002 timestamp[app2msf:1385476152571,msf2net:-1385476152571,net2msf:30038,msf2app:30038] errMsg:wait serverResp timeout
11-26 22:29:44.047    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:29:49.047    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:29:54.047    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:29:55.594    6760-9362/com.taobao.taobao:PushService_v1 E/SyncHttp.client﹕ request url error:[http://apoll.m.taobao.com/activeip/]
11-26 22:29:55.594    6760-9362/com.taobao.taobao:PushService_v1 E/HostClient﹕ host exception
11-26 22:29:57.524      135-157/? E/Cryptfs﹕ not running with encryption, aborting
11-26 22:29:57.532    9757-9771/? E/SQLiteLog﹕ (1) no such table: Account
11-26 22:29:59.047    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:30:01.446    6760-6994/com.taobao.taobao:PushService_v1 E/SyncHttp.client﹕ request url error:[http://apoll.m.taobao.com/activeip/]
11-26 22:30:01.453    6760-6994/com.taobao.taobao:PushService_v1 E/HostClient﹕ host exception
11-26 22:30:02.203   23933-9631/me.imid.fuubo E/com.ning.http.client.providers.jdk.JDKAsyncHttpProvider﹕ Unable to resolve host "api.weibo.com": No address associated with hostnameUnable to resolve host "api.weibo.com": No address associated with hostname
11-26 22:30:02.203   23933-9631/me.imid.fuubo E/com.ning.http.client.AndroidAsyncHandler﹕ java.net.ConnectException: Unable to resolve host "api.weibo.com": No address associated with hostname
11-26 22:30:04.086    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:30:04.735    9797-9797/? E/dalvikvm﹕ Could not find class 'com.taobao.statistic.TBSAE', referenced from method com.alipay.android.alipass.a.a.a.e
11-26 22:30:09.071    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:30:14.071    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:30:19.071    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:30:24.071    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:30:29.071    9420-9440/com.gracecode.tracker E/Tracker﹕ Index 0 requested, with a size of 0
11-26 22:30:29.289      420-443/system_process E/Sensors﹕ poll() failed (Interrupted system call)
```

**Comment by mingcheng** [comment]
http://developer.android.com/reference/android/app/Fragment.html 

All subclasses of Fragment must include a public empty constructor. The framework will often re-instantiate a fragment class when needed, in particular during state restore, and needs to be able to find this constructor to instantiate it. If the empty constructor is not available, a runtime exception will occur in some cases during state restore.
